<div class="container" id="widget-menu">
    <div class="row">
        <div id="widget_post">
            <?php if ($this->data): ?>
                <?php foreach ($this->data as $entity) : ?>
                    <div class="list_post">
                        <div class="list_post_topo">
                            <div class="list_post_topo_titulo">
                                <a href="<?= $this->basePath('posts/'.$entity->getLink()) ?>">
                                    <?php echo $entity->getTitulo(); ?>
                                </a>
                            </div>
                            <p>
                                Postado em <?= $this->formatDate($entity->getDateCreate())?>, em <?= $entity->getIdcategoria()->getNome()?>
                            </p>
                        </div>
                        <div class="list_post_corpo">
                            <img class="aligncenter" title="<?php echo $entity->getTitulo(); ?>" src="<?php echo $entity->getImagem(); ?>" alt="<?php echo $entity->getTitulo(); ?>" width="508" height="185">
                            <p>
                                <?= $entity->getResumo() ?>
                            </p>
                        <a href="<?= $this->basePath('posts/'.$entity->getTitulo()) ?>" target="_blank">Mais ...</a>
                        </div>
                        
                    </div>
                <?php endforeach; ?>
                <?php else:?>
            <h2>
                Não Existe Postagens
            </h2>
            <?php endif;?>

        </div>
        <div id="widget-menu-list-lateral">
            <div id="ultimas_noticias">
                <h1>Últimas Postagens</h1>
                <ul>
                    <?= $this->render_Ultimas_Noticas(); ?> 
                </ul>
            </div>

            <?= $this->render_Parceiros(); ?>

        </div>
    </div>
</div>