<div class="container" id="widget-menu">
    <div class="row">
        <div id="widget_post">
            <?php if ($this->data): ?>
                <?php foreach ($this->data as $entity) : ?>
                    <article class="list_post">
                        <?php if ($entity->getImagem()): ?>
                            <a href="<?= $this->basePath('posts/' . $entity->getLink()) ?>" title="<?= $entity->getTitulo(); ?>">
                                <img class="img-responsive" src="<?= $entity->getImagem() ?>" alt="<?= $entity->getTitulo(); ?>">
                            </a>

                        <?php endif; ?>
                        <header>

                            <h1>
                                <a href="<?= $this->basePath('posts/' . $entity->getLink()) ?>" title="<?= $entity->getTitulo(); ?>">
                                    <?= $entity->getTitulo(); ?>
                                </a>
                            </h1>
                            <div class="data-post">
                                Postado em <?= $this->formatDate($entity->getDateCreate()) ?>, por <?= $entity->getIdcategoria()->getNome() ?>
                            </div>
                        </header>
                        <hr/>
                        <div class="list_post_corpo">
                            <p>
                                <?= $entity->getResumo() ?>
                            </p>
                            Tags | 
                        </div>

                    </article>
                <?php endforeach; ?>
            <?php else: ?>
                <h2>
                    Não Existe Postagens
                </h2>
            <?php endif; ?>

        </div>
        <div id="widget-menu-list-lateral">
            <?= $this->render_Ultimas_Noticas(); ?> 


            <?= $this->render_Parceiros(); ?>

        </div>
    </div>
</div>