<?php
//echo $this->partial('partiais/_slider.phtml');
echo $this->render_Slider();
?>

<div class="container" id="widget-menu">
    <div class="row">
        <?= $this->render_Categoria(); ?>
        <div id="widget-menu-list-lateral">
            <div id="ultimas_noticias">
                <h1>Últimas Postagens</h1>
                <ul>
                    <li>Receita Federal Libera IRRF 2016</li>
                    <li>Tribunal de Contas Parabenisa a Prodata Informatica</li>
                    <li>Receita Federal Libera IRRF 2016</li>
                    <li>Tribunal de Contas Parabenisa a Prodata Informatica</li>
                    <li>Receita Federal Libera IRRF 2016</li>
                </ul>
            </div>
            
                <?= $this->render_Parceiros(); ?>

        </div>
    </div>
</div>
