<?php
//echo $this->partial('partiais/_slider.phtml');
echo $this->render_Slider();
?>

<div class="container" id="widget-menu">
    <div class="row">
        <div id="widget-menu-list">
            <div class="box">
                <i class="glyphicon glyphicon-list-alt " aria-hidden="true"></i>
                <h2>Dicas de Marketing</h2>
                <p>Diversas dicas e textos de motivação</p>
                <a href="http://www.sitecontabil.com.br/dicas_marketing/" target="_blank">mais</a>
            </div>
            <div class="box">
                <i class="glyphicon glyphicon-folder-close " aria-hidden="true"></i>
                <h2>Dicas de Marketing</h2>
                <p>Diversas dicas e textos de motivação</p>
                <a href="http://www.sitecontabil.com.br/dicas_marketing/" target="_blank">mais</a>
            </div>
            <div class="box">
                <i class="glyphicon glyphicon-list-alt " aria-hidden="true"></i>
                <h2>Dicas de Marketing</h2>
                <p>Diversas dicas e textos de motivação</p>
                <a href="http://www.sitecontabil.com.br/dicas_marketing/" target="_blank">mais</a>
            </div>
            <div class="box">
                <i class="glyphicon glyphicon-list-alt " aria-hidden="true"></i>
                <h2>Dicas de Marketing</h2>
                <p>Diversas dicas e textos de motivação</p>
                <a href="http://www.sitecontabil.com.br/dicas_marketing/" target="_blank">mais</a>
            </div>
            <div class="box">
                <i class="glyphicon glyphicon-list-alt " aria-hidden="true"></i>
                <h2>Dicas de Marketing</h2>
                <p>Diversas dicas e textos de motivação</p>
                <a href="http://www.sitecontabil.com.br/dicas_marketing/" target="_blank">mais</a>
            </div>


        </div>
        <div id="widget-menu-list-lateral">
            <div id="ultimas_noticias">
                <h1>Últimas Postagens</h1>
                <ul>
                    <li>Receita Federal Libera IRRF 2016</li>
                    <li>Tribunal de Contas Parabenisa a Prodata Informatica</li>
                    <li>Receita Federal Libera IRRF 2016</li>
                    <li>Tribunal de Contas Parabenisa a Prodata Informatica</li>
                    <li>Receita Federal Libera IRRF 2016</li>
                </ul>
            </div>
            <div class="col-md-12" id="publicidade-lateral"> 
                <h1>Parceiros </h1>

                <img src="imagem/Publicidade_ou_marketing.jpg" alt="" width="292" height="190"/>
            </div>
        </div>
    </div>

</div>