<?php echo $this->doctype(); ?>
<?php
if ($this->render_Empresa() != false) {
    $icone = $this->render_Empresa()->getLogoico();
    $logo = $this->render_Empresa()->getLogo();
    $empresa = $this->render_Empresa()->getNome();
} else {
    $icone = 'imagem/default/php_logo.ico';
    $logo = 'imagem/default/php_logo.png';
    $empresa = "ZF2";
}
?> 
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate($empresa))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(
                        array(
                    'rel' => 'shortcut icon',
                    'href' => $this->basePath($icone)), 'PREPEND')
                ->prependStylesheet($this->basePath('css/site/default.css'))
                ->prependStylesheet($this->basePath('css/vendor/fortawesome/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('css/vendor/plugins.css'));
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('/js/bootstrap.min.js'))
                ->prependFile($this->basePath('/js/jquery-2.2.3.min.js'))
        ?>

    </head>
    <body>

        <header><!-- Inicio da Header -->
            <div class="container" id="container"> <!--Inicio do Container -->
                <div id="topo"><!--Inicio da Div Topo -->
                    <div id="logo">
                        <a href="<?= $this->url('inicio') ?>" title="Inloco Assessoria e Serviço">
                            <img src="<?= $this->basePath($logo) ?>" class="img-responsive" alt="Inloco Assessoria & Serviço" />
                        </a>
                    </div>
                    <div id="pesquisa"><!--Inicio da Div pesquisa  -->
                        <p>Olá, Seja bem-Vindo <a href="<?= $this->url('login') ?>"> Área Restrita </a> </p>
                        <form action="">
                            <div class="input-group">
                                <input type="text" name="buscar" class="form-control" id="buscar" required placeholder="Pesquisar no Site... " />
                                <span class="input-group-btn">
                                    <button class="btn btn-info btn-lg" type="submit">
                                        <i class="glyphicon glyphicon-search"></i>
                                    </button>
                                </span> 
                            </div> <!--Fim Input de Psequisa-->
                        </form> <!--Fim Formulario de Pesquisa Topo -->
                    </div> <!--Fim pesquisa -->
                </div> <!--Fim Topo -->
            </div> <!--Fim Container -->
        </header><!-- Fim da Header -->
        <?php $partial = array('partials/_site_navigation.phtml', 'default') ?>
        <?php $this->navigation('navigationSite')->menu()->setPartial($partial) ?>
        <?php echo $this->navigation('navigationSite')->menu() ?>

        <?php echo $this->content; ?>
        <footer>
            <div class="container">
                <div class="content" id="footer-sidebar">
                    <div class="footer-widget footer-widget--about">
                        <a href="<?= $this->url('inicio') ?>" title="inloco assessoria e serviços">
                            <img src="<?= $this->basePath($logo) ?>" class="img-responsive" alt="Inloco Assessoria & Serviço" />
                        </a>
                        <p>
                            <?php
                            if ($this->render_Empresa() != FALSE) {
                                echo ($this->render_Empresa()->getMimidescrempre() ? $this->render_Empresa()->getMimidescrempre() : '');
                            }
                            ?>
                        </p>
                    </div>
                    <div class="footer-widget">
                        <div class="widget__title">
                            <span class="glyphicon glyphicon-education"></span> 
                            <p>Menu Principal</p>
                        </div>

                        <ul>
                            <li>
                                Página Principal
                            </li>
                            <li>
                                Contato
                            </li>
                            <li>
                                Empresa
                            </li>
                            <li>
                                Serviços
                            </li>
                        </ul>
                    </div>
                    <div class="footer-widget">
                        <div class="widget__title">
                            <span class="glyphicon glyphicon-pencil"></span> 
                            <p>Localização</p>
                        </div>
                        <?php if ($this->render_Empresa() != FALSE): ?>
                            <address>
                                <strong><?= ($this->render_Empresa()->getNome() ? $this->render_Empresa()->getNome() : ''); ?></strong><br>
                                <strong>Endereço:</strong><?= ($this->render_Empresa()->getEndereco() ? $this->render_Empresa()->getEndereco() : ''); ?><br>
                                <strong>CEP.</strong> <?= ($this->render_Empresa()->getCep() ? $this->render_Empresa()->getCep() : ''); ?> <br>
                                <strong>Horario:</strong><?= ($this->render_Empresa()->getHorario() ? $this->render_Empresa()->getHorario() : ''); ?> <br>
                                <strong>Telefone:</strong> <?= ($this->render_Empresa()->getTelefone() ? $this->render_Empresa()->getTelefone() : ''); ?>
                            </address>
                            <iframe src="<?= ($this->render_Empresa()->getgoogleMaps() ? $this->render_Empresa()->getgoogleMaps() : ''); ?>"  frameborder="0" style="border:0" allowfullscreen></iframe>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
            <div id="redes-sociais">
                <div class="container">
                    <div class="content">
                        <div id="redes-sociais__container">
                            <ul id="redes-sociais__icons">
                                <li>
                                    <a href="#" class="icon icon--facebook" title=""></a>
                                </li>
                                <li>
                                    <a href="#" class="icon icon--twitter" title=""></a>
                                </li>
                                <li>
                                    <a href="#" class="icon icon--youtube" title=""></a>
                                </li>
                                <li>
                                    <a href="#" class="icon icon--gplus" title=""></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </body>
</html>
