<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script>tinymce.init({
  selector: 'textarea.TextTinymce',
   menubar: false,
  plugins: [
    'advlist autolink lists link image charmap print preview anchor',
    'searchreplace visualblocks code fullscreen',
    'insertdatetime media table contextmenu paste code'
  ],
  toolbar: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
  content_css: '//www.tinymce.com/css/codepen.min.css'
});</script>

<div class="row">
    <div class="col-xs-12">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#fa-icons" data-toggle="tab">View <?= $this->router; ?></a></li>
                <li><a href="#Contato" data-toggle="tab">Contato</a></li>
                <li><a href="#Empresa" data-toggle="tab">Empresa</a></li>
                <li><a href="#Servicos" data-toggle="tab">Serviços</a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="fa-icons">
                    <div class="box-body">
                        <?php
                        echo $this->partial('partials/flashMesseger.phtml', array('error' => $this->error, 'success' => $this->success));
                        ?>

                        <?php
                        $form = $this->form;
                        $this->formElementErrors()
                                ->setMessageOpenFormat(
                                        '<div class="alert alert-error">' .
                                        '<button type="button" class="close" data-dismiss="alert">' .
                                        '<i class="fa fa-times"></i>' .
                                        '</button>')
                                ->setMessageCloseString('</div>')
                                ->render($form);
                        $form->setAttribute('role', 'form')
                                ->setAttribute('action', $this->url("dashboard/$this->router/editar", array('controller' => "dashboard/$this->router", 'action' => 'editar', 'id' => $this->id)));
                        $form->prepare();
                        
                      
                        
                        
                        echo $this->form()->openTag($form);
                        echo $this->renderForm($form, ['pcontatos','pempresa' , 'pservicos']);
                        echo $this->form()->closeTag($form);
                        ?>
                    </div>
                </div>
                <div class="tab-pane" id="Contato">
                    <?php
                        echo $this->form()->openTag($form);
                        echo $this->renderFormRow($form->get('pcontatos'));
                        echo $this->FormRow($form->get('Salvar'));
                        echo $this->form()->closeTag($form);
                    ?>
                </div>

                <div class="tab-pane" id="Empresa">
                    <?php
                        echo $this->form()->openTag($form);
                        echo $this->renderFormRow($form->get('pempresa'));
                        echo $this->FormRow($form->get('Salvar'));
                        echo $this->form()->closeTag($form);
                    ?>
                </div>

                <div class="tab-pane" id="Servicos">
                    <?php
                        echo $this->form()->openTag($form);
                        echo $this->renderFormRow($form->get('pservicos'));
                        echo $this->FormRow($form->get('Salvar'));
                        echo $this->form()->closeTag($form);
                    ?>
                </div>


            </div><!-- /.tabs-content -->
        </div><!-- /.nav-tabs-custom -->
    </div><!-- /.col -->
</div><!-- /.row -->

<!--*************** Corpo da pagina ***************-->




