<?php $errors = $this->formElementErrors()->render($element, array('class' => 'text-error')); ?>
<?php if (!$element instanceof Zend\Form\Element\Button) : ?>
    <div class="form-group">
        <?php if ($element->getLabel()) : ?>
            <label for="exampleInputEmail1"><?php echo $this->formLabel($element) ?></label>
        <?php endif; ?>
        <?php echo $this->formElement($element); ?>

        <?php if ($errors): ?>
            <small><?php echo $errors ?></small>
        <?php endif; ?>

    </div>
<?php else: ?>
<div class="box-footer">
    <?= $this->formElement($element); ?> 
    
</div>
<?php endif; ?>



