<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script>tinymce.init({
  selector: 'textarea',
   menubar: false,
  plugins: [
    'advlist autolink lists link image charmap print preview anchor',
    'searchreplace visualblocks code fullscreen',
    'insertdatetime media table contextmenu paste code'
  ],
  toolbar: 'undo redo | insert | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image',
  content_css: '//www.tinymce.com/css/codepen.min.css'
});</script>

<div class="box box-primary ">
    <div class="box-header with-border">
        <!--*************** Title da Pagina ***************-->
        <h3 class="box-title">View Inserir <?= $this->router ;?></h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
        <!--*************** Fim Title da Pagina ***************-->
    </div>
    <!--*************** Corpo da pagina ***************-->
    <div class="box-body">
        <?php
            echo $this->partial('partials/flashMesseger.phtml', array('error' => $this->error, 'success' => $this->success));
        ?>
        
        <?php
            $form = $this->form;
            $this->formElementErrors()
                    ->setMessageOpenFormat(
                              '<div class="alert alert-error">'.
                                    '<button type="button" class="close" data-dismiss="alert">'.
                                        '<i class="fa fa-times"></i>'.
                                    '</button>')
                    ->setMessageCloseString('</div>')
                    ->render($form);
            $form->setAttribute('role', 'form')   
                 ->setAttribute('action',$this->url("dashboard/$this->router/inserir", array('controller' => "dashboard/".$this->router,'action' => 'inserir')));
            $form->prepare();

        
            echo $this->form()->openTag($form); 
            echo $this->renderForm($form); 
            echo $this->form()->closeTag($form);
        ?>
    </div>
    <!--*************** Fim Corpo da pagina***************-->
</div>




