<a class="btn btn-success" href="<?php
echo $this->url("dashboard/$this->router/editar", array(
    'controller' => 'controller',
    'action' => 'editar',
    'id' => $entity->getId()));
?>">
    <i class="glyphicon glyphicon-edit"></i>
</a>
<a class="btn btn-danger" href="<?php
echo $this->url("dashboard/$this->router/excluir", array(
    'controller' => 'controller',
    'action' => 'excluir',
    'id' => $entity->getId()));
?>">
    <i class="glyphicon glyphicon-remove"></i>
</a>