<ul class="sidebar-menu">
    <li class="header">MAIN NAVIGATION</li>
    <?php foreach ($this->container as $page): ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
        <?php // when using partials we need to manually check for ACL conditions ?>
        <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) continue; ?>
        <?php $hasChildren = $page->hasPages() ?>
        <?php if (!$hasChildren): ?>
            <li <?php if ($page->isActive()) echo 'class="active"' ?>>
                <a href="<?php echo $page->getHref() ?>">
                    <?php if ($page->get('icon')): ?>
                        <i class="<?php echo $page->get('icon') ?>"></i>
                    <?php endif ?>
                    <span><?php ($page->getLabel()) ?></span>
                </a>
            </li>
        <?php else: ?>
            <li class="treeview
            <?php foreach ($page->getPages() as $child): ?>
                <?php if ($child->hasPages()):?>    
                    <?php foreach ($child->getPages() as $child): ?>
                        <?php if ($child->isActive()): ?>
                                active
                                <?php break; ?>
                        <?php endif; ?>
                    <?php endforeach ?>
                <?php else: ?>
                    <?php if ($child->isActive()): ?>
                        active
                        <?php break; ?>        
                    <?php endif ?>
                <?php endif ?>
            <?php endforeach ?>
                ">
                <a href="#">
                    <?php if ($page->get('icon')): ?>
                        <i class="<?php echo $page->get('icon') ?>"></i>
                    <?php endif ?>
                    <span>
                        <?php echo $page->getLabel() ?>
                    </span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu" >
                    <?php foreach ($page->getPages() as $child): ?>
                        <?php $filhos_child = $child->hasPages(); ?>
                        <?php if (!$filhos_child): ?>   
                            <?php // when using partials we need to manually check for ACL conditions ?>
                            <?php if (!$child->isVisible() || !$this->navigation()->accept($child)) continue; ?>
                            <li class="<?php if ($child->isActive()) echo 'active'; ?>">
                                <a href="<?php echo $child->getHref() ?>">
                                    <i class="fa fa-circle-o"></i>
                                    <?php echo $this->translate($child->getLabel()) ?>
                                </a>
                            </li>
                        <?php else: ?>
                            <li class="treeview 
                            <?php foreach ($child->getPages() as $filhoschild): ?>
                                <?php if ($filhoschild->isActive()): ?>
                                        active
                                        <?php break; ?>
                                    <?php endif ?>     
                                <?php endforeach; ?>">
                                <a href="<?php echo $child->getHref() ?>">
                                    <i class="fa fa-circle-o"></i>
                                    <?php echo $this->translate($child->getLabel()) ?>
                                    <span class="pull-right-container">
                                        <i class="fa fa-angle-left pull-right"></i>
                                    </span>
                                </a>
                                <ul class="treeview-menu" >
                                    <?php foreach ($child->getPages() as $filhoschild): ?>
                                        <?php if (!$filhoschild->isVisible() || !$this->navigation()->accept($filhoschild)) continue; ?>
                                        <li class="<?php if ($filhoschild->isActive()) echo 'active'; ?>">
                                            <a href="<?php echo $filhoschild->getHref() ?>">
                                                <i class="fa fa-circle-o"></i>
                                                <?php echo $this->translate($filhoschild->getLabel()) ?>
                                            </a>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>

                            </li>   
                        <?php endif; ?>    
                    <?php endforeach ?>
                </ul>
            </li>
        <?php endif ?>
    <?php endforeach ?>
</ul>