
<?php $this->headScript()->prependFile($this->basePath('js/dashboard/scripts/teste.js')); ?>
<script type="text/css">

</script>
<div class="row">
    <div class="col-xs-12">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <li class="active"><a href="#fa-icons" data-toggle="tab">View <?= $this->router; ?></a></li>
                <li><a href="#Ordem" data-toggle="tab">Ordem de Exibição </a></li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane active" id="fa-icons">
                    <div class="box-body">
                        <?php if ($this->data->count() > 0): ?>
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th> # </th>
                                        <th style="width: 100px">
                                            <em class="fa fa-cog"></em>
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($this->data as $entity) : ?>
                                        <tr>
                                            <td> <?php echo $entity->getId(); ?> </td>
                                            <td>
                                                <a class="btn btn-success" href="<?php
                                                echo $this->url("dashboard/$this->router/editar", array(
                                                    'controller' => 'controller',
                                                    'action' => 'editar',
                                                    'id' => $entity->getId()));
                                                ?>">
                                                    <i class="glyphicon glyphicon-edit"></i>
                                                </a>
                                                <a class="btn btn-danger" href="<?php
                                                echo $this->url("dashboard/$this->router/excluir", array(
                                                    'controller' => 'controller',
                                                    'action' => 'excluir',
                                                    'id' => $entity->getId()));
                                                ?>">
                                                    <i class="glyphicon glyphicon-remove"></i>
                                                </a>
                                            </td>
                                        </tr>        
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        <?php else: ?>
                            <p>  Nenhum registro encontrado </p>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="tab-pane" id="Ordem">

                    <input type="button" id="Atualizar" value="Atualizar" />    
                    <div id="OrderList" class="numberlist">
                        <?php if ($this->data->count()): ?>
                            <ol>
                                <?php foreach ($this->data as $entity) : ?>
                                    <li id="widgetArray_<?= $entity->getId() ?>"> <a href="#"><?= $entity->getTitulo() ?> - Ordem  <?= $entity->getOrderExibir() ?></a></li>
                                <?php endforeach; ?>
                            </ol>    
                        <?php endif; ?>
                    </div>

                </div>

            </div><!-- /.tabs-content -->
        </div><!-- /.nav-tabs-custom -->
    </div><!-- /.col -->
</div><!-- /.row -->





