<div class="box box-primary">
    <div class="box-header with-border">
        <!--*************** Title da Pagina ***************-->
        <h3 class="box-title">View <?= $this->router ;?></h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
        <!--*************** Fim Title da Pagina ***************-->
    </div>
    <!--*************** Corpo da pagina ***************-->
    <div class="box-body">
        <?php
            echo $this->partial('partials/flashMesseger.phtml', array('error' => $this->error, 'success' => $this->success));
        ?>
        <div class="table-responsive">
            <div class="panel panel-default panel-table">
                <div class="panel-heading">
                    <div class="row">

                        <div class="col col-xs-6 pull-right  text-right">
                            <a class="btn btn-success" href="<?php echo $this->url( "dashboard/$this->router/inserir") ;?>">
                                Novo Registro  <i class="glyphicon glyphicon-plus"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    
                </div>
                <div class="panel-footer">
                    <div class="row">
                        <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator', array('route' => "dashboard/$this->router/paginator")); ?>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

<?php $this->headScript()->prependFile($this->basePath('js/dashboard/scripts/teste.js')); ?>

<div id="sidebar">
    <?php if ($this->data->count()): ?>
        <ul>
            <?php foreach ($this->data as $entity) : ?>
                <li id="widgetArray_<?= $entity->getId() ?>"> <?= $entity->getTitulo() ?> - Ordem  <?= $entity->getOrder() ?> </li>
                <?php endforeach; ?>
        </ul>    
    <?php endif; ?>
</div>

<div id="Array">
    <p>Array Referente as posições</p>
</div>
